import { Finding, SeverityCounts } from '../types/sarif';
import { SeverityUtils } from '../utils/severity';

export class MarkdownFormatter {
    formatPrComment(
        counts: SeverityCounts,
        findings: Finding[],
        passed: boolean,
        threshold: string
    ): string {
        if (passed) {
            return this.formatPassedComment(counts);
        }

        return this.formatFailedComment(counts, findings, threshold);
    }

    private formatPassedComment(counts: SeverityCounts): string {
        return `# Quality Gate Passed

No findings exceeded the configured severity threshold.

## Summary

| Severity | Count |
| -------- | ----- |
| ${SeverityUtils.getSeverityBadge('critical')} | ${counts.critical} |
| ${SeverityUtils.getSeverityBadge('high')} | ${counts.high} |
| ${SeverityUtils.getSeverityBadge('medium')} | ${counts.medium} |
| ${SeverityUtils.getSeverityBadge('low')} | ${counts.low} |

**Total:** ${counts.total} finding(s)

---
_Generated by Quality Gate Action_`;
    }

    private formatFailedComment(
        counts: SeverityCounts,
        findings: Finding[],
        threshold: string
    ): string {
        const summary = `# Quality Gate Failed

Findings exceeded the **${threshold}** severity threshold.

## Summary

| Severity | Count |
| -------- | ----- |
| ${SeverityUtils.getSeverityBadge('critical')} | ${counts.critical} |
| ${SeverityUtils.getSeverityBadge('high')} | ${counts.high} |
| ${SeverityUtils.getSeverityBadge('medium')} | ${counts.medium} |
| ${SeverityUtils.getSeverityBadge('low')} | ${counts.low} |

**Total:** ${counts.total} finding(s)`;

        if (findings.length === 0) {
            return `${summary}

---
_Generated by Quality Gate Action_`;
        }

        const topFindings = findings.slice(0, 10);
        const findingsTable = this.formatFindingsTable(topFindings);
        const moreFindings = findings.length > 10
            ? `

**Showing top 10 of ${findings.length} findings.**

<details>
<summary>View all findings (${findings.length})</summary>

${this.formatFindingsTable(findings)}

</details>`
            : '';

        return `${summary}

## Findings (top ${topFindings.length})

${findingsTable}${moreFindings}

---
_Generated by Quality Gate Action_`;
    }

    private formatFindingsTable(findings: Finding[]): string {
        const headers = '| Severity | Rule | File | Line | Description |';
        const separator = '| -------- | ---- | ---- | ---- | ----------- |';

        const rows = findings.map(f => {
            const severity = SeverityUtils.getSeverityBadge(f.severity);
            const title = f.ruleName || f.ruleId;
            const message = this.truncateMessage(f.description || f.message);
            return `| ${severity} | \`${title}\` | \`${f.file}\` | ${f.line} | ${message} |`;
        });

        return [headers, separator, ...rows].join('\n');
    }

    private truncateMessage(message: string, maxLength: number = 120): string {
        if (message.length <= maxLength) {
            return message;
        }
        return message.substring(0, maxLength - 3) + '...';
    }

    formatStepSummary(
        counts: SeverityCounts,
        findings: Finding[],
        passed: boolean,
        threshold: string,
        duration: number
    ): string {
        const status = passed ? 'PASS' : 'FAIL';
        const duration_s = (duration / 1000).toFixed(2);

        return `# Quality Gate Results

**Status:** ${status}  
**Threshold:** ${threshold}  
**Duration:** ${duration_s}s

## Findings

| Severity | Count |
| -------- | ----- |
| Critical | ${counts.critical} |
| High | ${counts.high} |
| Medium | ${counts.medium} |
| Low | ${counts.low} |
| **Total** | **${counts.total}** |`;
    }

    formatJson(counts: SeverityCounts, findings: Finding[], passed: boolean, threshold: string) {
        return {
            status: passed ? 'PASS' : 'FAIL',
            threshold,
            counts,
            findings: findings.map(f => ({
                ruleId: f.ruleId,
                severity: f.severity,
                file: f.file,
                line: f.line,
                message: f.message,
                tool: f.tool,
            })),
        };
    }
}