import { Finding, SeverityCounts } from '../types/sarif';
import { SeverityUtils } from '../utils/severity';

export class MarkdownFormatter {
    formatPrComment(
        counts: SeverityCounts,
        findings: Finding[],
        passed: boolean,
        threshold: string
    ): string {
        if (passed) {
            return this.formatPassedComment(counts);
        }

        return this.formatFailedComment(counts, findings, threshold);
    }

    private formatPassedComment(counts: SeverityCounts): string {
        return `# ✅ Quality Gate Passed

No findings exceeded the configured severity threshold.

## Summary

| Severity | Count |
| -------- | ----- |
| 🔴 Critical | ${counts.critical} |
| 🟠 High | ${counts.high} |
| 🟡 Medium | ${counts.medium} |
| 🔵 Low | ${counts.low} |

**Total:** ${counts.total} finding(s)

---
_Generated by Quality Gate Action_`;
    }

    private formatFailedComment(
        counts: SeverityCounts,
        findings: Finding[],
        threshold: string
    ): string {
        const summary = `# ❌ Quality Gate Failed

Findings exceeded the **${threshold}** severity threshold.

## Summary

| Severity | Count |
| -------- | ----- |
| 🔴 Critical | ${counts.critical} |
| 🟠 High | ${counts.high} |
| 🟡 Medium | ${counts.medium} |
| 🔵 Low | ${counts.low} |

**Total:** ${counts.total} finding(s)`;

        if (findings.length === 0) {
            return `${summary}

---
_Generated by Quality Gate Action_`;
        }

        const findingsTable = this.formatFindingsTable(findings);
        const findingsSection =
            findings.length > 100
                ? `
## Findings (showing first 100 of ${findings.length})

<details>
<summary>Click to expand findings table</summary>

${findingsTable}

</details>`
                : `
## Findings

${findingsTable}`;

        return `${summary}${findingsSection}

---
_Generated by Quality Gate Action_`;
    }

    private formatFindingsTable(findings: Finding[]): string {
        const headers = '| Severity | Rule | File | Line | Message |';
        const separator = '| -------- | ---- | ---- | ---- | ------- |';

        const rows = findings.slice(0, 100).map(f => {
            const severity = SeverityUtils.getSeverityEmoji(f.severity);
            const message = this.truncateMessage(f.message);
            return `| ${severity} ${f.severity} | \`${f.ruleId}\` | \`${f.file}\` | ${f.line} | ${message} |`;
        });

        return [headers, separator, ...rows].join('\n');
    }

    private truncateMessage(message: string, maxLength: number = 80): string {
        if (message.length <= maxLength) {
            return message;
        }
        return message.substring(0, maxLength - 3) + '...';
    }

    formatStepSummary(
        counts: SeverityCounts,
        findings: Finding[],
        passed: boolean,
        threshold: string,
        duration: number
    ): string {
        const status = passed ? '✅ PASS' : '❌ FAIL';
        const duration_s = (duration / 1000).toFixed(2);

        return `# Quality Gate Results

**Status:** ${status}  
**Threshold:** ${threshold}  
**Duration:** ${duration_s}s

## Findings

| Severity | Count |
| -------- | ----- |
| Critical | ${counts.critical} |
| High | ${counts.high} |
| Medium | ${counts.medium} |
| Low | ${counts.low} |
| **Total** | **${counts.total}** |`;
    }

    formatJson(counts: SeverityCounts, findings: Finding[], passed: boolean, threshold: string) {
        return {
            status: passed ? 'PASS' : 'FAIL',
            threshold,
            counts,
            findings: findings.map(f => ({
                ruleId: f.ruleId,
                severity: f.severity,
                file: f.file,
                line: f.line,
                message: f.message,
                tool: f.tool,
            })),
        };
    }
}